title: Комментарии
href: index.md
items:
  - name: Обзор методов
    href: index.md
  - name: Получить перечень методов и их описаний
    href: task-comment-item-get-manifest.md
  - name: Добавить комментарий
    href: task-comment-item-add.md
  - name: Изменить комментарий
    href: task-comment-item-update.md
  - name: Получить комментарий по идентификатору
    href: task-comment-item-get.md
  - name: Получить список комментариев
    href: task-comment-item-get-list.md
  - name: Удалить комментарий
    href: task-comment-item-delete.md
  - name: Проверить доступные действия над задачей
    href: task-comment-item-is-action-allowed.md
  - name: События
    include:
      path: events-comment/b24-toc.yaml
      mode: link